services:
  - type: web
    name: flow-space-frontend
    env: static
    buildCommand: "chmod +x build.sh && ./build.sh"
    staticPublishPath: ./Flow-Space/build/web
    envVars:
      - key: FLUTTER_WEB_CANVASKIT_URL
        value: https://cdn.jsdelivr.net/gh/flutter/canvaskit@master
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*
        name: Pragma
        value: no-cache
      - path: /*
        name: Expires
        value: 0
